CREATE TABLE IF NOT EXISTS knowledge_document (
  id BIGINT PRIMARY KEY,
  doc_code VARCHAR(100) NOT NULL,
  title VARCHAR(255) NOT NULL,
  module VARCHAR(50) NOT NULL,
  source_type VARCHAR(50) NOT NULL,
  content_format VARCHAR(30) NOT NULL DEFAULT 'MARKDOWN',
  chunk_strategy VARCHAR(50) NOT NULL DEFAULT 'SEMANTIC_MARKDOWN',
  version VARCHAR(30) DEFAULT 'v1.0',
  status VARCHAR(30) NOT NULL DEFAULT 'ENABLED',
  content_hash VARCHAR(64) DEFAULT NULL,
  remark VARCHAR(500) DEFAULT NULL,
  created_by BIGINT DEFAULT NULL,
  updated_by BIGINT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_knowledge_document_doc_code (doc_code),
  KEY idx_knowledge_document_module (module),
  KEY idx_knowledge_document_source_type (source_type),
  KEY idx_knowledge_document_status (status)
);

CREATE TABLE IF NOT EXISTS knowledge_chunk (
   id BIGINT PRIMARY KEY,
   doc_id BIGINT NOT NULL,
   chunk_code VARCHAR(120) NOT NULL,
   title VARCHAR(255) NOT NULL,
   module VARCHAR(50) NOT NULL,
   source_type VARCHAR(50) NOT NULL,
   biz_type VARCHAR(80) DEFAULT NULL,
   operation_type VARCHAR(80) DEFAULT NULL,
   entity_name VARCHAR(100) DEFAULT NULL,
   scenario VARCHAR(255) DEFAULT NULL,
   keywords VARCHAR(500) DEFAULT NULL,
   content TEXT NOT NULL,
   content_hash VARCHAR(64) NOT NULL,
   sort_order INT NOT NULL DEFAULT 0,
   status VARCHAR(30) NOT NULL DEFAULT 'ENABLED',
   vector_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
   vector_error_message VARCHAR(1000) DEFAULT NULL,
   created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
   updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   UNIQUE KEY uk_knowledge_chunk_chunk_code (chunk_code),
   KEY idx_knowledge_chunk_doc_id (doc_id),
   KEY idx_knowledge_chunk_module (module),
   KEY idx_knowledge_chunk_operation_type (operation_type),
   KEY idx_knowledge_chunk_status (status),
   KEY idx_knowledge_chunk_vector_status (vector_status)
);